import React from 'react';
import { Info, AlertTriangle } from 'lucide-react';
import { cn } from '@/lib/utils';

interface AIAnalysisBannerProps {
  className?: string;
  variant?: 'info' | 'warning';
  compact?: boolean;
}

export function AIAnalysisBanner({ className, variant = 'info', compact = false }: AIAnalysisBannerProps) {
  const isWarning = variant === 'warning';
  return (
    <div
      className={cn(
        'flex items-start gap-2.5 rounded-card border px-4 py-3',
        isWarning
          ? 'bg-amber-50 dark:bg-amber-950/15 border-amber-200 dark:border-amber-800/40'
          : 'bg-teal-50 dark:bg-teal-950/15 border-teal-200 dark:border-teal-800/40',
        className
      )}
      role="note"
      aria-label="AI analysis disclaimer"
    >
      {isWarning
        ? <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" aria-hidden="true" />
        : <Info className="w-4 h-4 text-teal-500 shrink-0 mt-0.5" aria-hidden="true" />
      }
      <p className={cn(
        compact ? 'text-ds-caption' : 'text-ds-small',
        isWarning ? 'text-amber-800 dark:text-amber-300' : 'text-teal-800 dark:text-teal-300'
      )}>
        <span className="font-semibold">AI-Assisted Analysis — Decision Support Only.</span>{' '}
        <span className="opacity-75">
          Results are generated by a prototype AI model and must be verified by a qualified clinician before any clinical action.
        </span>
      </p>
    </div>
  );
}
